import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

List<String> clubs = [
  "3D Modeling Club",
  "3D Printing Club",
  "A/V Club",
  "Academic Council",
  "Accounting Club",
  "Aerospace Engineering Club",
  "African Heritage Club",
  "American Meteorological Society",
  "American Society of Mechanical Engineers",
  "Anatomy Club",
  "Animal Rights Club",
  "Animation Club",
  "Anime Club",
  "Anthropology Club",
  "Arabic Culture Club",
  "Architecture Club",
  "Armenian Club",
  "Art History Club",
  "Artificial Intelligence Club",
  "Asian Cooking Club",
  "Astrology Club",
  "Astronomy Club",
  "Aviation Club",
  "Baking Club",
  "Ballroom Dancing Club",
  "Beauty Club",
  "Beekeeping Club",
  "Bible Study",
  "BioBuilder Club",
  "Biochem Club",
  "Biology Club",
  "Biomedical Engineering Club",
  "Black History Club",
  "Board Games Club",
  "Bollywood Club",
  "Book Club",
  "Botany Club",
  "Brazilian Club",
  "Break Dancing Club",
  "Broadcasting Club",
  "Business Club",
  "Call of Duty Club",
  "Calligraphy Club",
  "Cancer Awareness Club",
  "Car Club",
  "Cartooning Club",
  "Ceramics Club",
  "Chemistry Club",
  "Chess Club",
  "Chick-fil-A Leader Academy",
  "Chinese Club",
  "Chinese Yoyo Club",
  "Civics Club",
  "Civil War Reenactors",
  "Classical Music Club",
  "Climate Action Club",
  "Coffee Club",
  "Comics Club",
  "Computer Science Club",
  "Conservation Club",
  "Consulting Club",
  "Cooking Club",
  "Cornhole Club",
  "Cosmetology Club",
  "Criminal Justice Club",
  "Crossfit Club",
  "Culinary Club",
  "Current Events Club",
  "Cycling Club",
  "Dance Club",
  "Data Science Club",
  "Debate Club",
  "Dungeons & Dragons Club",
  "Eastern European Culture Club",
  "Eco Club",
  "Economics Club",
  "Electrical Engineering Club",
  "Electronics Club",
  "Energy Team",
  "Engineering Club",
  "Entrepreneurship Club",
  "Environmental Club",
  "Equestrian Club",
  "Ethics Club",
  "European History Club",
  "Fair Trade for Life",
  "Fantasy Sports Club",
  "Fashion Club",
  "Film Club",
  "Filmmaking Club",
  "Finance Club/Financial Literacy Club",
  "Fishing Club",
  "Foreign Affairs Club",
  "Foreign Film Club",
  "Forensic Science Club",
  "French Club",
  "Friendship Club",
  "Future Doctors of America",
  "Future Educators of America",
  "Future Engineers of America",
  "Future Farmers of America",
  "Future Law Professionals of America",
  "Future Physicians Club",
  "Future Teachers of America",
  "Game Development Club/Gaming Club",
  "Gardening Club",
  "Geography Club",
  "Geology Club",
  "German Club",
  "Graphic Design Club",
  "Grilling Club",
  "Gun Reform Club",
  "Hiking Club",
  "Hindi Club",
  "Hip Hop Club",
  "History Club",
  "Indian Culture Club",
  "International Club",
  "International Food Club",
  "International Relations Club",
  "Investing Club",
  "Irish Culture Club",
  "Jazz Club",
  "Journalism Club",
  "Junior Statesmen of America",
  "Junior World Affairs Council",
  "Karaoke Club",
  "Knitting Club",
  "Korean Club",
  "K-Pop Dance",
  "LARP Club",
  "Latin American Culture Club",
  "Latin Club",
  "Leadership Club",
  "Life Sciences Club",
  "Literature Club",
  "Magic Club",
  "Mahjong Club",
  "Makerspace Club",
  "Mandarin Club",
  "Marine Biology Club",
  "Marketing Club",
  "Math Club",
  "Meditation Club",
  "Mental Health Club",
  "Meteorology Club",
  "Microbiology Club",
  "Microfinance Club",
  "Middle East Culture Club",
  "Military History Club",
  "Minecraft Club",
  "Morning Announcements ",
  "Mosaic Club",
  "Mountaineers Club",
  "Multicultural Club",
  "National Chinese Honor Society",
  "Nature Club",
  "Neurodiversity Club",
  "Neuroscience Club",
  "Nutrition Club",
  "Origami Club",
  "Outdoors Club",
  "Pen Pal Club",
  "Performing Arts Club",
  "Philosophy Club",
  "Photography Club",
  "Physics Club",
  "Ping Pong Club",
  "Poetry Club",
  "Political Discussion Club",
  "Politics Club",
  "Pre-Med Club",
  "Psychology Club",
  "Quidditch Club",
  "Religion Club",
  "Renaissance Faires",
  "Rifle Club",
  "ROBLOX Club",
  "Robotics Club",
  "Rock Climbing Club",
  "Rocketry Club",
  "Russian Club",
  "Sailing Club",
  "Science Club",
  "Shakespeare Club",
  "Sign Language Club",
  "Skateboard Club",
  "Slam Poetry Club",
  "Smash Club",
  "Spanish Club",
  "Sports Medicine Club",
  "Sportswriting Club",
  "Statistics Club",
  "STEM Club",
  "Strength and Fitness Club",
  "Sustainability Club",
  "TED-X",
  "Toastmasters Club",
  "Urban Planning Club",
  "Vegan Club",
  "Vegan/Vegetarian Club",
  "Veterans Support Club",
  "Vietnamese Culture Club",
  "Women In Science and Engineering (WISE)",
  "World War II Club",
  "Young Entrepreneurs Club",
  "Young Investors Societ"
];

class ClubsView extends StatelessWidget {
  const ClubsView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          const Scaffold(
            backgroundColor: Colors.grey,
            resizeToAvoidBottomInset: false,
          ),    
          SingleChildScrollView(
            child: Column(
              children: [
                const Spacer(),
                const Spacer(),
                for (int i = 0; i < clubs.length; i++)
                  MaterialButton(
                    onPressed: () {
                      launchUrl(Uri.parse('https://www.google.com/search?q=${clubs[i]}'));
                    },
                    padding: const EdgeInsets.all(20),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    color: Colors.white,
                    minWidth: 310,
                    height: 60,
                    child: Text(
                      clubs[i],
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 20,
                        color: Colors.black,
                      ),
                    ),
                  ),
              ],
            ),
          ),
        ],
      ),
      appBar: AppBar(
        title: const Text('Clubs'),
      ),
    );
  }
}
